<center><img src='https://drive.google.com/uc?id=1_utx_ZGclmCwNttSe40kYA6VHzNocdET' height="60"></center>

AI TECH - Akademia Innowacyjnych Zastosowań Technologii Cyfrowych. Programu Operacyjnego Polska Cyfrowa na lata 2014-2020
<hr>

<center><img src='https://drive.google.com/uc?id=1BXZ0u3562N_MqCLcekI-Ens77Kk4LpPm'></center>

<center>
Projekt współfinansowany ze środków Unii Europejskiej w ramach Europejskiego Funduszu Rozwoju Regionalnego 
Program Operacyjny Polska Cyfrowa na lata 2014-2020,
Oś Priorytetowa nr 3 "Cyfrowe kompetencje społeczeństwa" Działanie  nr 3.2 "Innowacyjne rozwiązania na rzecz aktywizacji cyfrowej" 
Tytuł projektu:  „Akademia Innowacyjnych Zastosowań Technologii Cyfrowych (AI Tech)”
    </center>

# Logistic regression

In this exercise you will train a logistic regression model via gradient descent in two simple scenarios.
 
The general setup is as follows:
* we are given a set of pairs $(x, y)$, where $x \in R^D$ is a vector of real numbers representing the features, and $y \in \{0,1\}$ is the target,
* for a given $x$ we model the probability of $y=1$ by $h(x):=g(w^Tx)$, where $g$ is the sigmoid function: $g(z) = \frac{1}{1+e^{-z}}$,
* to find the right $w$ we will optimize the so called logarithmic loss: $J(w) = -\frac{1}{n}\sum_{i=1}^n y_i \log{h(x_i)} + (1-y_i) \log{(1-h(x_i))}$,
* with the loss function in hand we can improve our guesses iteratively:
    * $w_j^{t+1} = w_j^t - \text{step_size} \cdot \frac{\partial J(w)}{\partial w_j}$,
* we can end the process after some predefined number of epochs (or when the changes are no longer meaningful).

Let's start with the simplest example - linear separated points on a plane. 

In [1]:
import numpy as np

np.random.seed(123)

# these parametrize the line
a = 0.3
b = -0.2
c = 0.001

# True/False mapping
def lin_rule(x, noise=0.):
    return a * x[0] + b * x[1] + c + noise < 0.

# Just for plotting
def get_y_fun(a, b, c):
    def y(x):
        return - x * a / b - c / b
    return y

lin_fun = get_y_fun(a, b, c)

In [2]:
# Training data

n = 500
range_points = 1
sigma = 0.05

X = range_points * 2 * (np.random.rand(n, 2) - 0.5)
y = [lin_rule(x, sigma * np.random.normal()) for x in X]

print(X[:10])
print(y[:10])

[[ 0.39293837 -0.42772133]
 [-0.54629709  0.10262954]
 [ 0.43893794 -0.15378708]
 [ 0.9615284   0.36965948]
 [-0.0381362  -0.21576496]
 [-0.31364397  0.45809941]
 [-0.12285551 -0.88064421]
 [-0.20391149  0.47599081]
 [-0.63501654 -0.64909649]
 [ 0.06310275  0.06365517]]
[False, True, False, False, False, True, False, True, True, False]


Let's plot the data.

In [3]:
import plotly.express as px

# plotly has a problem with coloring boolean values, hence stringify
# see https://community.plotly.com/t/plotly-express-scatter-color-not-showing/25962
fig = px.scatter(x=X[:, 0], y=X[:, 1], color=list(map(str, y)))
x_range = [np.min(X[:, 0]), np.max(X[:, 1])]
fig.add_scatter(x=x_range, y=list(map(lin_fun, x_range)), name='ground truth border')
fig.show()

Now, let's implement and train a logistic regression model. You should obtain accuracy of at least 96%.

In [4]:
################################################################
# TODO: Implement logistic regression and compute its accuracy #
################################################################

def sigmoid(x):
  return 1/(1 + np.exp(-x))

def gradient(xs, ys, ws):
  return -np.dot(xs.T, ys-sigmoid(np.dot(xs,ws)))/xs.shape[0]

def loss(xs, ys, ws):
  z = sigmoid(np.dot(xs, ws))
  return -np.mean(ys*np.log(z) + (1-ys)*np.log(1-z))

lr = 0.005
epochs = 100000

def predict(xs, ws):
  return sigmoid(np.dot(xs, ws))

def fit(xs, ys, lr, epochs, improve_threshold=0.001):
  prev_losses = []
  xs = np.c_[np.array(xs), np.ones(xs.shape[0])]
  ws = np.zeros(xs.shape[1])
  while True:
    for i in range(epochs):
      ws -= lr * gradient(xs, ys, ws)
    loss_val = loss(xs, ys, ws)
    iter = len(prev_losses)
    pred = predict(xs, ws)
    pred[pred >= 0.5] = 1
    pred[pred < 0.5] = 0
    acc = np.count_nonzero(ys == pred)/n
    print('Iter: {:>3} Loss: {:8.8f}, Accuracy: {:8.8f}'.format(iter, loss_val, acc), 'Weights:', [round(w,4) for w in ws])
    if prev_losses and prev_losses[-1] - loss_val < improve_threshold:
      break
    else:
      prev_losses.append(loss_val)
  return ws

xs = np.array(X)
ys = np.array(y)

W = fit(xs, ys, lr, epochs)


Iter:   0 Loss: 0.11389173, Accuracy: 0.96400000 Weights: [-8.4647, 5.8261, 0.0469]
Iter:   1 Loss: 0.10191627, Accuracy: 0.96600000 Weights: [-10.4412, 7.2059, 0.0454]
Iter:   2 Loss: 0.09745687, Accuracy: 0.96600000 Weights: [-11.6586, 8.0543, 0.0474]
Iter:   3 Loss: 0.09522231, Accuracy: 0.96600000 Weights: [-12.5225, 8.6564, 0.0502]
Iter:   4 Loss: 0.09394051, Accuracy: 0.96600000 Weights: [-13.1775, 9.1129, 0.0531]
Iter:   5 Loss: 0.09314529, Accuracy: 0.96600000 Weights: [-13.6937, 9.4728, 0.0558]


Let's visually asses our model. We can do this by using our estimates for $a,b,c$.

In [5]:
#################################################################
# TODO: Pass your estimates for a,b,c to the get_y_fun function #
#################################################################
lin_fun2 = get_y_fun(W[0], W[1], W[2])

fig = px.scatter(x=X[:, 0], y=X[:, 1], color=list(map(str, y)))
x_range = [np.min(X[:, 0]), np.max(X[:, 1])]
fig.add_scatter(x=x_range, y=list(map(lin_fun, x_range)), name='ground truth border')
fig.add_scatter(x=x_range, y=list(map(lin_fun2, x_range)), name='estimated border')
fig.show()

Let's now complicate the things a little bit and make our next problem nonlinear.

In [6]:
# Parameters of the ellipse
s1 = 1.
s2 = 2.
r = 0.75
m1 = 0.15
m2 = 0.125

# 0/1 mapping, checks whether we are inside the ellipse
def circle_rule(x, y, noise=0.):
    return 1 if s1 * (x - m1) ** 2 + s2 * (y - m2) ** 2 + noise < r ** 2 else 0

In [7]:
# Training data

n = 500
range_points = 1

sigma = 0.1

X = range_points * 2 * (np.random.rand(n, 2) - 0.5)

y = [circle_rule(x, y, sigma * np.random.normal()) for x, y in X]

print(X[:10])
print(y[:10])

[[ 0.18633789  0.87560968]
 [-0.81999293  0.61838609]
 [ 0.22604784  0.28001611]
 [ 0.9846182  -0.35783437]
 [-0.27962406  0.07170775]
 [ 0.2501677  -0.37650776]
 [ 0.41264707 -0.8357508 ]
 [-0.61039043 -0.97349628]
 [ 0.49924022  0.89579621]
 [ 0.537422   -0.65425777]]
[0, 0, 1, 0, 1, 1, 0, 0, 0, 0]


Let's plot the data.

In [8]:
import plotly.graph_objects as go

fig = px.scatter(x=X[:, 0], y=X[:, 1], color=list(map(str, y)))

xgrid = np.arange(np.min(X[:, 0]), np.max(X[:, 0]), 0.003)
ygrid = np.arange(np.min(X[:, 1]), np.max(X[:, 1]), 0.003)
contour =  go.Contour(
        z=np.vectorize(circle_rule)(*np.meshgrid(xgrid, ygrid, indexing="ij")),
        x=xgrid, 
        y=ygrid
    )
fig.add_trace(contour)
fig.show()

Now, let's train a logistic regression model to tackle this problem. Note that we now need a nonlinear decision boundary. You should obtain accuracy of at least 90%.

Hint: 
<sub><sup><sub><sup><sub><sup>
Use feature engineering.
</sup></sub></sup></sub></sup></sub>

In [9]:
################################################################
# TODO: Implement logistic regression and compute its accuracy #
################################################################
xs = np.array(X)
ys = np.array(y)
def scale(xs):
  return np.c_[xs, xs[:,0]**2, xs[:,1]**2, xs[:, 0] * xs[:, 1]]


def predict_sec(xs, ws):
  xs = np.c_[np.array(xs), np.ones(xs.shape[0])]
  return sigmoid(np.dot(xs, ws))

new_xs = scale(xs)
W = fit(new_xs, ys, 0.5, 100000)


Iter:   0 Loss: 0.08606800, Accuracy: 0.96200000 Weights: [5.0009, 10.0928, -19.768, -39.8729, 0.5957, 10.317]
Iter:   1 Loss: 0.08593745, Accuracy: 0.96200000 Weights: [5.2277, 10.5606, -20.7248, -41.7913, 0.6441, 10.8197]


Let's visually asses our model. 

Contrary to the previous scenario, converting our weights to parameters of the ground truth curve may not be straightforward. It's easier to just provide predictions for a set of points in $R^2$.

In [10]:
h = .02

xgrid = np.arange(np.min(X[:, 0]), np.max(X[:, 0]), h)
ygrid = np.arange(np.min(X[:, 1]), np.max(X[:, 1]), h)

xx, yy = np.meshgrid(xgrid, ygrid, indexing="ij")
X_plot = np.c_[xx.ravel(), yy.ravel()]

print(X_plot.shape)

_X = np.concatenate([X_plot, X_plot**2], axis=1)

preds = (predict_sec(scale(X_plot), W) > 0.5)
print(preds.shape)


(10000, 2)
(10000,)


In [26]:
preds

array([False, False, False, ..., False, False, False])

In [40]:
preds_2 = np.array(list(map(int, preds)))
preds_2

array([0, 0, 0, ..., 0, 0, 0])

In [41]:
fig = px.scatter(x=X[:, 0], y=X[:, 1], color=list(map(str, y)))

xx, yy = np.meshgrid(xgrid, ygrid, indexing="ij")

contour = go.Contour(z=preds_2.reshape(len(xgrid), len(ygrid)), x=xgrid, y=ygrid)
fig.add_trace(contour)
fig.show()

<center><img src='https://drive.google.com/uc?id=1BXZ0u3562N_MqCLcekI-Ens77Kk4LpPm'></center>