<center><img src='https://drive.google.com/uc?id=1Pl06DMKpHRrRLQiuADOrZIlc9aosJYEq' height="60"></center>

AI TECH - Akademia Innowacyjnych Zastosowań Technologii Cyfrowych. Programu Operacyjnego Polska Cyfrowa na lata 2014-2020
<hr>

<center><img src='https://drive.google.com/uc?id=1PioHCAlQTt8LWChoMysPErSOrxOfAW0R'></center>

<center>
Projekt współfinansowany ze środków Unii Europejskiej w ramach Europejskiego Funduszu Rozwoju Regionalnego 
Program Operacyjny Polska Cyfrowa na lata 2014-2020,
Oś Priorytetowa nr 3 "Cyfrowe kompetencje społeczeństwa" Działanie  nr 3.2 "Innowacyjne rozwiązania na rzecz aktywizacji cyfrowej" 
Tytuł projektu:  „Akademia Innowacyjnych Zastosowań Technologii Cyfrowych (AI Tech)”
    </center>



# Bootcamp - introduction to machine learning: NumPy & Pandas


## What is NumPy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, basic linear algebra, statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance. There are several important differences between NumPy arrays and the standard Python sequences:

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, **such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences**.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. In other words, in order to efficiently use much (perhaps even most) of today’s scientific/mathematical Python-based software, just knowing how to use Python’s built-in sequence types is insufficient - one also needs to know how to use NumPy arrays.



from: https://numpy.org/doc/stable/user/whatisnumpy.html

In [2]:
import numpy as np
import matplotlib.pyplot as plt

## Array creation

There are multiple ways to create an array, try examples below.

### From nested lists

In [2]:
array_1d = np.array([1, 2, 3, 4, 5])
array_1d

array([1, 2, 3, 4, 5])

In [3]:
array_2d = np.array(
  [
    [1,  2,  3,  4,  5 ],
    [6,  7,  8,  9,  10],
    [11, 12, 13, 14, 15]
  ]
)
array_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [4]:
array_3d = np.array(
  [
    [
      [1,  2,  3,  4,  5 ],
      [6,  7,  8,  9,  10],
      [11, 12, 13, 14, 15],
    ],
    [
      [16, 17, 18, 19, 20],
      [21, 22, 23, 24, 25],
      [26, 27, 28, 29, 30],
    ]
  ]
)
array_3d

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]])

### Using zeros / ones / full



In [5]:
shape = (2, 3)

np.zeros(shape)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones(shape)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
fill_value = 42
np.full(shape, fill_value)

array([[42, 42, 42],
       [42, 42, 42]])

### Using zeros_like / ones_like / full_like

In [8]:
np.zeros_like(array_2d)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [9]:
np.ones_like(array_2d)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
fill_value = 42
np.full_like(array_2d, fill_value)

array([[42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42]])

### Using arange / linspace (1D arrays only)

which are used to fill an array with values from the interval $[low, high]$ with specific step or number of points.

In [11]:
start = 0
stop  = 1
step  = 0.1

np.arange(start, stop, step)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [12]:
np.arange(start, stop + 1e-4, step)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [13]:
n_steps = int((stop-start)/step) + 1
np.linspace(start, stop, n_steps)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

### Using identity / diag (2D arrays only)
 to create identity or diagonal (with optional offset) matrices.

In [14]:
n = 4
np.identity(n)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.diag([1, 2, 3, 4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [16]:
offset = 1
np.diag([1, 2, 3], offset)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

### Using meshgrid
For 1D arrays X_1, ..., X_n meshgrid behavior is specified as follows

```
G_1, ..., G_n = np.meshgrid(X_1, ..., X_n, indexing='ij')
G_j[i_1, i_2, ..., i_n] = X_j[i_j]

G_1, ..., G_n = np.meshgrid(X_1, ..., X_n, indexing='xy')  # default indexing
G_j[i_2, i_1, i_3, ..., i_n] = X_j[i_j]
```

what facilitates creating coordinate grids,




In [17]:
x = np.array([1, 2, 3], dtype=np.int)
y = np.array([4, 5, 6, 7], dtype=np.int)

x_grid, y_grid = np.meshgrid(x, y, indexing='ij')

such as:

In [18]:
x_grid

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

In [19]:
y_grid

array([[4, 5, 6, 7],
       [4, 5, 6, 7],
       [4, 5, 6, 7]])

In [20]:
x_grid.shape == y_grid.shape == (len(x), len(y))

True

### Using tile & repeat
to create an array filled with "repeating pattern".

In [21]:
array = np.array([0,1,2])

In [22]:
np.tile(array, 2)

array([0, 1, 2, 0, 1, 2])

In [23]:
np.tile(array, (2, 1))

array([[0, 1, 2],
       [0, 1, 2]])

In [24]:
np.repeat(array, 2)

array([0, 0, 1, 1, 2, 2])

In [25]:
np.repeat(array, 2, axis=0)

array([0, 0, 1, 1, 2, 2])

In [26]:
np.repeat(array.reshape(1, -1), 2, axis=0)

array([[0, 1, 2],
       [0, 1, 2]])

In [27]:
np.repeat(array.reshape(1, -1), 2, axis=1)

array([[0, 0, 1, 1, 2, 2]])

## NumPy dtypes

Full list of NumPy dtypes is available here: https://numpy.org/doc/stable/user/basics.types.html

Among which there are 5 basic numerical types representing booleans (bool), integers (int), unsigned integers (uint) floating point (float) and complex.

Data-types can be used as arguments to the dtype keyword that many numpy functions or methods accept, in particular array creation routines.

See examples below.

In [28]:
np.array([1, 2, 3, 4, 5], dtype=np.int)

array([1, 2, 3, 4, 5])

In [29]:
np.array([1, 2, 3, 4, 5], dtype=np.float)

array([1., 2., 3., 4., 5.])

In [30]:
np.array([1, 2, 3, 4, 5], dtype=np.complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

Types can be casted as follows

In [31]:
float_array   = np.array([1, 2, 3, 4, 5], dtype=np.float)
complex_array = float_array.astype(np.complex)

float_array, float_array.dtype

(array([1., 2., 3., 4., 5.]), dtype('float64'))

In [32]:
complex_array, complex_array.dtype

(array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j]), dtype('complex128'))

## Saving / loading data

### Using savetxt / loadtxt

to process a single 1D/2D array in human readable format. File created with `savetxt` can be easily accessed with a text editor

In [33]:
data = np.array(
  [
    [1, 2],
    [3, 4],
  ]
)

np.savetxt('data.txt', data)
!cat data.txt

1.000000000000000000e+00 2.000000000000000000e+00
3.000000000000000000e+00 4.000000000000000000e+00


as well as seamlessly loaded back with `loadtxt`.


In [34]:
np.loadtxt('data.txt')

array([[1., 2.],
       [3., 4.]])

File format can be specified, see https://numpy.org/doc/stable/reference/generated/numpy.savetxt.html for reference

In [35]:
np.savetxt('data.txt', data, fmt='%.2f')
!cat data.txt

1.00 2.00
3.00 4.00


In [38]:
np.savetxt('data.txt', data, fmt='%d')
!cat data.txt

1 2
3 4


Nevertheless information regarding dtype is not preserved.

In [36]:
np.loadtxt('data.txt')

array([[1., 2.],
       [3., 4.]])

In [39]:
np.loadtxt('data.txt', dtype=np.int)

array([[1, 2],
       [3, 4]])

`savetxt` method can be used to save an array in csv format, we only need to specify the proper delimiter

In [40]:
np.savetxt('data.csv', data, delimiter=',', fmt='%.2f')
!cat data.csv

1.00,2.00
3.00,4.00


as well as loaded back

In [41]:
np.loadtxt('data.csv', delimiter=',')

array([[1., 2.],
       [3., 4.]])

### Using save / load 
to process an arbitrary array in binary format. Unfortunalety the resulting file is not human readable. On the other these methods can handle array of orbitrary shape and preserve the underlying dtype.

In [43]:
data = np.array(
  [
    [
      [1, 2],
      [3, 4],
    ]
  ]
)

np.save('data.npy', data)

!cat data.npy

�NUMPYv{'descr': '<i8', 'fortran_order': False, 'shape': (1, 2, 2), }                                                       


In [44]:
np.load('data.npy')

array([[[1, 2],
        [3, 4]]])

In [45]:
np.load('data.npy').dtype == data.dtype

True

### Using savez / load

to process **multiple** arbitrary arrays in binary format. The result of the load operation is an object of dictionary-like structure.

In [46]:
array_1 = np.array([1, 2, 3], dtype=np.int)
array_2 = np.array([[4, 5, 6]], dtype=np.float)
array_3 = np.array([[[7, 8, 9]]], dtype=np.complex)

np.savez('data.npz', array_1, array_2, some_name=array_3)
loaded_data = np.load('data.npz')
loaded_data.files

['some_name', 'arr_0', 'arr_1']

In [47]:
loaded_data['arr_0']

array([1, 2, 3])

In [48]:
loaded_data['arr_1']

array([[4., 5., 6.]])

In [49]:
loaded_data['some_name']

array([[[7.+0.j, 8.+0.j, 9.+0.j]]])

### Using savez_compressed / load 
to process multiple arbitrary arrays in binary format with compression. It behaves just as savez but the resulting file is also compressed, what save space on the disk. 



In [50]:
shape = (1000, 1000)
data = np.ones(shape)
np.savez('data_uncompressed.npz', data)
np.savez_compressed('data_compressed.npz', data)

We can compare the filesizes with `ls` command.

In [51]:
!ls data_*compressed.npz -lh

-rw-r--r-- 1 root root  12K Oct  4 16:31 data_compressed.npz
-rw-r--r-- 1 root root 7.7M Oct  4 16:31 data_uncompressed.npz


## Shape manipulation
It possible tha change the structure of data in the array. See examples below.

#### Reshape

In [52]:
data = np.arange(0, 12, 1, dtype = np.int)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [53]:
data.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
data.reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [55]:
data_reshaped = data.reshape(2, 3, 2)
data_reshaped

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [56]:
shape = data_reshaped.shape
shape

(2, 3, 2)

#### Inferring **one** dimension while usigng reshape method

In [57]:
data.reshape(6, -1)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [58]:
data.reshape(-1, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [59]:
data.reshape(3, 2, -1)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

#### Flatten

In [60]:
data_reshaped.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

#### Adding / deleting dummy dimensions
Facilites vectorized arithmetic with conjunction with broadcasting mechanism (explained later)

In [61]:
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [62]:
data.shape

(12,)

In [63]:
data_expanded1 = np.expand_dims(data, 0)
data_expanded1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [64]:
data_expanded1.shape

(1, 12)

In [65]:
data_expanded2 = np.expand_dims(data, 1)
data_expanded2

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [66]:
data_expanded2.shape

(12, 1)

In [67]:
data_expanded3 = np.expand_dims(data_expanded1, 2)
data_expanded3

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]]])

In [68]:
data_expanded3.shape

(1, 12, 1)

In [69]:
data_squeezed = data_expanded3.squeeze()
data_squeezed

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [70]:
data_squeezed.shape

(12,)

#### Transposing

For 2D arrays it behaves just as expected (performs matrix transpose).

In [71]:
data = np.arange(0, 4, 1).reshape(2, 2)
data

array([[0, 1],
       [2, 3]])

In [72]:
data.transpose()

array([[0, 2],
       [1, 3]])

For higher dimensional arrays its best visualized via observing how the shape changes.

In [73]:
shape = (1, 2, 3, 4)
data = np.ones(shape)
data.shape

(1, 2, 3, 4)

The default behavior is to flip dimensions.

In [74]:
data.transpose().shape

(4, 3, 2, 1)

However other permutations of dimensions might be specified.

In [75]:
dimensions_permutation = [1, 0, 3, 2]
data.transpose(dimensions_permutation).shape

(2, 1, 4, 3)

`.T` is a shortand for `.transpose()`

In [76]:
data.T.shape

(4, 3, 2, 1)

## Concatenation & stacking
The following methods are used to merge multiple arrays (with compatible shapes) into one array.

### concatenate
used to join a sequence of arrays along an **existing** axis.

In [77]:
shape = (4,)
array_1 = np.full(shape, 1)
array_2 = np.full(shape, 2)

array_1, array_2

(array([1, 1, 1, 1]), array([2, 2, 2, 2]))

In [78]:
np.concatenate([array_1, array_2, array_1])

array([1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1])

In [79]:
array_1 = array_1.reshape(1, -1)
array_2 = array_2.reshape(1, -1)

array_1, array_2

(array([[1, 1, 1, 1]]), array([[2, 2, 2, 2]]))

The default axis to join on is 0

In [80]:
np.concatenate([array_1, array_2, array_1])

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [1, 1, 1, 1]])

But it can be changed

In [81]:
np.concatenate([array_1, array_2, array_1], axis=1)

array([[1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1]])

### stack

used to stack a sequence of arrays along a **new** axis.

In [82]:
shape = (4,)
array_1 = np.full(shape, 1)
array_2 = np.full(shape, 2)

array_1, array_2

(array([1, 1, 1, 1]), array([2, 2, 2, 2]))

In [83]:
np.stack([array_1, array_2, array_1])

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [1, 1, 1, 1]])

In [84]:
np.stack([array_1, array_2, array_1], axis=1)

array([[1, 2, 1],
       [1, 2, 1],
       [1, 2, 1],
       [1, 2, 1]])


### hstack, vstack and dstack 
stand for horizontal, vertical and depthwise stacking

In [85]:
np.hstack([array_1, array_2, array_1])

array([1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1])

In [86]:
np.vstack([array_1, array_2, array_1])

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [1, 1, 1, 1]])

In [87]:
np.dstack([array_1, array_2, array_1])

array([[[1, 2, 1],
        [1, 2, 1],
        [1, 2, 1],
        [1, 2, 1]]])

## Mathematical operations
As stated before 

> NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

Let us observe some examples.



In [88]:
x = np.arange(0, 3, 1)
y = np.arange(3, 6, 1)

x, y

(array([0, 1, 2]), array([3, 4, 5]))

#### Elementwise

Basic mathematical operations will be applied to the arrays elementwise.

In [89]:
2 * x

array([0, 2, 4])

In [90]:
x * 2

array([0, 2, 4])

In [91]:
np.sin(x)

array([0.        , 0.84147098, 0.90929743])

In [92]:
x**2

array([0, 1, 4])

The same applies to the binary (taking two arguments) operators and arrays of the same shape.

In [93]:
x + y

array([3, 5, 7])

In [94]:
x * y

array([ 0,  4, 10])

In [95]:
x / y

array([0.  , 0.25, 0.4 ])

In [96]:
y ** x

array([ 1,  4, 25])

#### Broadcasting

When arrays have different shapes the broadcasting mechanism comes into play.

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations.

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimensions and works its way left. Two dimensions are compatible when

- they are equal, or
- one of them is 1

If these conditions are not met, a `ValueError: operands could not be broadcast together` exception is thrown, indicating that the arrays have incompatible shapes. The size of the resulting array is the size that is not 1 along each axis of the inputs.

from: https://numpy.org/devdocs/user/basics.broadcasting.html

In [97]:
x_shape = (2, 4)
y_shape = (2, 1)

x = np.ones(x_shape)
y = np.ones(y_shape)

(x + y).shape

(2, 4)

In [101]:
x_shape =    (2, 4)
y_shape = (3, 1, 1)

x = np.ones(x_shape)
y = np.ones(y_shape)

(x + y).shape

(3, 2, 4)

In [105]:
x_shape = (   1, 4)
y_shape = (3, 2, 1)

x = np.ones(x_shape)
y = np.ones(y_shape)

(x + y).shape

(3, 2, 4)

### Matrix / tensor operations
NumPy package wouldn't be complete without means to manipulate arrays other than elementwise operations, such as most common linear algebra functionalities. See the examples below.

#### Matrix multiplication

can be performed with `matmul` method

In [106]:
a = np.eye(3)
a[2,2] = 2
b = np.arange(0, 3, 1).reshape(3, 1)

a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 2.]])

In [107]:
b

array([[0],
       [1],
       [2]])

In [108]:
np.matmul(a, b)

array([[0.],
       [1.],
       [4.]])

or `@` operand

In [109]:
a @ b

array([[0.],
       [1.],
       [4.]])

Be mindfull of its varying behaviour for different input shapes

- If both arguments are 2-D they are multiplied like conventional matrices.
- If either argument is N-D, N > 2, it is treated as a stack of matrices residing in the last two indexes and broadcast accordingly.
- If the first argument is 1-D, it is promoted to a matrix by prepending a 1 to its dimensions. After matrix multiplication the prepended 1 is removed.
- If the second argument is 1-D, it is promoted to a matrix by appending a 1 to its dimensions. After matrix multiplication the appended 1 is removed.

from: https://numpy.org/doc/stable/reference/generated/numpy.matmul.html

#### Dot product

can be performed using `dot` method.

In [110]:
x = np.arange(0, 3, 1)
y = np.arange(3, 6, 1)

x, y

(array([0, 1, 2]), array([3, 4, 5]))

In [111]:
np.dot(x, y)

14

Be mindfull of its varying behaviour for different input shapes

- If both a and b are 1-D arrays, it is inner product of vectors (without complex conjugation).

- If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred.

- If either a or b is 0-D (scalar), it is equivalent to multiply and using numpy.multiply(a, b) or a * b is preferred.

- If a is an N-D array and b is a 1-D array, it is a sum product over the last axis of a and b.

- If a is an N-D array and b is an M-D array (where M>=2), it is a sum product over the last axis of a and the second-to-last axis of b:

  ```
  dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
  ```

from: https://numpy.org/doc/stable/reference/generated/numpy.dot.html


#### Einstein summation convention
Einstein summation convention provide a concise way of expressing multilinear operations. You can look it up here https://mathworld.wolfram.com/EinsteinSummation.html and its NumPy specification here https://numpy.org/doc/stable/reference/generated/numpy.einsum.html.

Take a look a the following ilustrative examples.


In [112]:
data = np.tri(3)
data

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [113]:
np.einsum('ij->ji', data)  # transpose

array([[1., 1., 1.],
       [0., 1., 1.],
       [0., 0., 1.]])

In [114]:
np.einsum('ij->i', data)  # row sum

array([1., 2., 3.])

In [115]:
np.einsum('ij->j', data)  # column sum

array([3., 2., 1.])

In [116]:
np.einsum('ii->i', data)  # diagonal

array([1., 1., 1.])

In [117]:
vector = np.ones(3)
vector

array([1., 1., 1.])

In [118]:
np.einsum('ij,j->i', data, vector)  # matrix multiplication (matrix x vector)

array([1., 2., 3.])

In [119]:
np.einsum('ij,jk->ik', data, vector.reshape(3, 1))  # matrix multiplication (matrix x matrix)

array([[1.],
       [2.],
       [3.]])

## Other operations

### Aggregations: mean / var
Very often we are required to calculate some aggregations with respoect to speciic dimensions of an array, such as mean or variance.

In [120]:
data = np.arange(0, 20, 1).reshape(4, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

By default the whole array is aggregated

In [121]:
data.mean()

9.5

But aggregations can also be applied axiswise

In [122]:
data.mean(axis=0)

array([ 7.5,  8.5,  9.5, 10.5, 11.5])

In [123]:
data.mean(axis=1)

array([ 2.,  7., 12., 17.])

In [124]:
data.var(axis=0)

array([31.25, 31.25, 31.25, 31.25, 31.25])

In [125]:
data.var(axis=1)

array([2., 2., 2., 2.])

### Aggregation: quantiles

Many more aggregations are possible, e.g. determining data quantiles.

In [126]:
data = np.linspace(1, 2, 101)

np.quantile(data, 0.3)

1.3

In [127]:
np.quantile(data, [0.3, 0.6])

array([1.3, 1.6])

### Sorting

Arrays can be sorted. By default sorting is performed with respoect to the last dimension

In [128]:
data = np.array([
  [1, 4, 2, 8, 5],
  [2, 3, 1, 9, 6],
  [8, 2, 3, 7, 4],  
])

np.sort(data)

array([[1, 2, 4, 5, 8],
       [1, 2, 3, 6, 9],
       [2, 3, 4, 7, 8]])

but sorting dimension can be explicitly specified.

In [129]:
np.sort(data, axis=0)

array([[1, 2, 1, 7, 4],
       [2, 3, 2, 8, 5],
       [8, 4, 3, 9, 6]])

In [130]:
np.sort(data, axis=1)

array([[1, 2, 4, 5, 8],
       [1, 2, 3, 6, 9],
       [2, 3, 4, 7, 8]])

You can also get the "sorting permutations" that can be used in conjunction with advanced indexing (introduced below).

In [131]:
np.argsort(data, axis=0)

array([[0, 2, 1, 2, 2],
       [1, 1, 0, 0, 0],
       [2, 0, 2, 1, 1]])

In [132]:
np.argsort(data, axis=1)

array([[0, 2, 1, 4, 3],
       [2, 0, 1, 4, 3],
       [1, 2, 4, 3, 0]])

## Indexing

Allows selecting items and subarrays. It can be also used to modify fragments of an array.

### Basic indexing

In [133]:
data = np.arange(0, 16, 1)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [134]:
data[10]

10

In [135]:
data[-2]

14

In [136]:
data[:5]

array([0, 1, 2, 3, 4])

In [137]:
data[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [138]:
data[-3:]

array([13, 14, 15])

It is also possible in higher dimensional setting


In [139]:
data = data.reshape(4, 4)
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [140]:
data[1, 1]

5

In [141]:
data[1, :]

array([4, 5, 6, 7])

One does not need to specify trailing colons `:`

In [142]:
data[:-2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

Note how the column selection is achiveved. In this case `:` can't be ommited.

In [143]:
data[:, -2:]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

One group of subsequent colons `:` can be replaced with `...`

In [144]:
data_reshaped = data.reshape(4, 2, 2)
data_reshaped

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]]])

In [145]:
data_reshaped[..., 0]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14]])

Note the difference

In [146]:
data_reshaped[:, 0]

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

### View & copies

Basic indexing routines presented above return views of the data in the underlying arrays. When the underlying array is modified the changes are reflected in the view.

In [147]:
data = np.arange(0, 16, 1).reshape(4, 4)
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [148]:
view = data[:, 3]
view

array([ 3,  7, 11, 15])

In [149]:
data *= 2
data

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [150]:
view

array([ 6, 14, 22, 30])

To "detach" view from the underlying array use `copy` method

In [151]:
view_copy = view.copy()
data *= 2
view, view_copy

(array([12, 28, 44, 60]), array([ 6, 14, 22, 30]))

Views are only possible when selecting with slices, then it's a matter of rememebering offset and stride only.

You can read more about this here: https://scipy-cookbook.readthedocs.io/items/ViewsVsCopies.html

### Advanced indexing

it is also possible to index with integer or boolean arrays

In [152]:
data = np.arange(0, 16, 1).reshape(4, 4)
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

We can select specific rows

In [153]:
data[[0, 3]]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

and columns.

In [154]:
data[:, [0, 3]]

array([[ 0,  3],
       [ 4,  7],
       [ 8, 11],
       [12, 15]])

Seleceting both together is a little more complicated

In [155]:
rows = [
 [0, 0],
 [3, 3]
]
columns = [
 [0, 3],
 [0, 3]
]
data[rows, columns]

array([[ 0,  3],
       [12, 15]])

Use indices shape to control the output shape.

In [156]:
rows = [0, 0, 3, 3]
columns = [0, 3, 0, 3]
data[rows, columns]

array([ 0,  3, 12, 15])

Bboolean arrays can be used as well, though they work somewhat differently.

In [157]:
index = (data % 3 == 0)
index

array([[ True, False, False,  True],
       [False, False,  True, False],
       [False,  True, False, False],
       [ True, False, False,  True]])

In [158]:
data[index]

array([ 0,  3,  6,  9, 12, 15])

Its most common use case is to update array entries based on some condition.

In [159]:
data[index] = -1
data

array([[-1,  1,  2, -1],
       [ 4,  5, -1,  7],
       [ 8, -1, 10, 11],
       [-1, 13, 14, -1]])

Detailed bahavior of indexing with boolean arrays is described here: https://numpy.org/doc/stable/reference/arrays.indexing.html#advanced-indexing

# NumPy Exercises

### Exercise: multiplication table
Create "{0, ..., 10} x {0, ..., 10} multiplication table" using only 
- `meshgrid` method,
- multiplication of 1D arrays, dummy dimensions and broadcasting mechanism.

In [170]:
### YOUR CODE BEGINS HERE ###
x = np.arange(1, 11, 1)
x_grid, y_grid = np.meshgrid(x, x, indexing='ij')
x_grid * y_grid
### YOUR CODE ENDS HERE ###

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [7]:
### YOUR CODE BEGINS HERE ###
x = np.arange(1, 11, 1)
x_exp = np.expand_dims(x, 1)
x_exp * x_exp.T
### YOUR CODE ENDS HERE ###

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

### Exercise: speed comparison 

In this exercise we will measure the speed imporovemnts due to NumPy implementation.

In [172]:
length = 10000
a = b = np.arange(length)

Write the code to calculate dotproduct of arrays `a` and `b` using only native Python funcions. Use `timeit` magic to time the execution.

In [174]:
%%timeit
### YOUR CODE BEGINS HERE ###
sum = 0
for i in range(len(a)):
  sum += a[i]*b[i]
### YOUR CODE ENDS HERE ###

100 loops, best of 5: 5.14 ms per loop


Now compare the execution time with `np.dot`.

In [173]:
%%timeit
### YOUR CODE BEGINS HERE ###
np.dot(a,b)
### YOUR CODE ENDS HERE ###

The slowest run took 7.24 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 11 µs per loop


### Exercise: vector operations
Calculate 
$$ \int_0^1 \sin(a\cdot2\pi x)\sin(b\cdot 2\pi x)dx $$ 
for 
- $a=b=1$,
- $a=1$ and $b=2$,

using discrete approximation of an integral and following NumPy functions: `linspace, sin, mean`


In [197]:
# Case a = b = 1
### YOUR CODE BEGINS HERE ###
x = np.linspace(0,1,1000000)
a = 1
b = 1
answer = np.mean(np.sin(a * 2 * np.pi * x) * np.sin(b * 2 * np.pi * x))
### YOUR CODE ENDS HERE ###

print(answer.round(4))
assert np.isclose(answer, 0.5)

0.5


In [196]:
# Case a = 1, b = 2
### YOUR CODE BEGINS HERE ###
x = np.linspace(0,1,1000000)
a = 1
b = 2
answer = np.mean(np.sin(a * 2 * np.pi * x) * np.sin(b * 2 * np.pi * x))
### YOUR CODE ENDS HERE ###
print(answer.round(4))
assert np.isclose(answer, 0)

0.0


### Exercise: vector operations ctd.

Let $a_j = j$. Calculate in a similar fashion matrix $(b_{ij})_{i,j=0, ..., 4}$, where
$$ b_{ij} = \int_0^1 \sin(a_i\cdot2\pi x)\sin(a_j\cdot 2\pi x)dx. $$ 

Try to structure your code in such a way that it would accept an arbitrary array `a`.

In [8]:
a = np.arange(5)

### YOUR CODE BEGINS HERE ###
x = np.linspace(0,1,1000000)
b = np.reshape(a, (-1, 1, 1))
a = np.reshape(a, (1, -1, 1))

answer = np.mean(np.sin(a*2*np.pi*x) * np.sin(b*2*np.pi*x), axis=2) 
### YOUR CODE ENDS HERE ###

print(answer.round(2))
assert np.isclose(answer, np.diag([0, 0.5, 0.5, 0.5, 0.5])).all()

[[ 0.   0.   0.   0.   0. ]
 [ 0.   0.5  0.  -0.   0. ]
 [ 0.   0.   0.5 -0.  -0. ]
 [ 0.  -0.  -0.   0.5 -0. ]
 [ 0.   0.  -0.  -0.   0.5]]


### Exercise: subarrays

Let us sample $n=100 000$ standard normal random variables. Calculate mean of values greater than zero.

In [9]:
np.random.seed(0)

n = 100000
sample = np.random.randn(n)

### YOUR CODE BEGINS HERE ###
answer = np.mean(sample[sample>0])
### YOUR CODE ENDS HERE ###

assert np.isclose(answer, np.sqrt(2/np.pi), rtol=0.01)

### Exercise: subarrays ctd.
Let us sample an array of random integers.
1. Select columns for which sum of its values gives remainder = 1 when divided by 3.
2. Change entries in that columns to ones.
3. Calculate sum of all entries.

In [10]:
np.random.seed(0)
sample = np.random.randint(0, 3, size=(10, 10))

### YOUR CODE BEGINS HERE ###
sample = sample.T
sample[np.mod(np.sum(sample, axis = 1), 3) == 1] = np.ones(sample.shape[1])
answer = np.sum(sample)
### YOUR CODE ENDS HERE ###

assert answer == 88


### Exercise: matrix multiplication & merging arrays

In this exercies we will approximate operator norm of some matrices.

1. Create an an array of $n=1000$ vectors $v\in\mathbb{R}^2$ "evenly spaced" on the unit circle. 
2. Combine given three matrices into one array.
3. Use **one** matrix multiplication operation with these arrays to obtain matrix products of all the vectors with all the matrices.
4. For each vector calculate its (euclidean) length.
5. Take maximum with respect to each matrix.
6. You should obtain three values representing approximations of operator norm of provided matrices.


In [11]:
matrix_1 = np.array([
  [1, 0],
  [0, 1]
])

matrix_2 = np.array([
  [1, 1],
  [1, 1]
])

matrix_3 = np.array([
  [1, 1],
  [0, 1]
])

### YOUR CODE BEGINS HERE ###
n = 1000
lin = np.linspace(0, 1, n)

combined_matrix = np.stack((matrix_1, matrix_2, matrix_3))

x = np.sin(2*np.pi*lin)
y = np.cos(2*np.pi*lin)
points = np.stack((x, y))

multiplied = np.matmul(combined_matrix, points)
answer = np.max(np.sqrt(multiplied[:, 0]**2 + multiplied[:, -1]**2), axis=1)
### YOUR CODE ENDS HERE ###

print(answer.round(4))
assert np.isclose(answer, [1, 2, (1+np.sqrt(5))/2]).all()

[1.    2.    1.618]


## Other NumPy functionalities
NumPy package impelemnts plethora of mathematical functionalities, not covered in this tutorial. NumPy User guide and API Reference are great starting point to discover those functionalities:
- https://numpy.org/doc/stable/user/
- https://numpy.org/doc/stable/reference/


# What is pandas?

Pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool,
built on top of the Python programming language.

It is meant for manipulating datasets in tabular format, that is 2D arrays with rows representing observations and columns representing variables, the so called **DataFrames**.

from: https://pandas.pydata.org/

### Creating dataframes

In the most basic form you just specify 2D array of values

In [5]:
import pandas as pd

df = pd.DataFrame(
    np.arange(0, 16, 1).reshape(4, 4)
)

df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

It is possible to additionally specify columns and index labels

In [6]:
df = pd.DataFrame(
    np.arange(0, 16, 1).reshape(4, 4),
    columns = ['column_1', 'column_2', 'column_3', 'column_4'],
    index   = ['a', 'b', 'c', 'd']
)

df

column_1  column_2  column_3  column_4
a         0         1         2         3
b         4         5         6         7
c         8         9        10        11
d        12        13        14        15

as well as type of entries

In [7]:
df = pd.DataFrame(
    np.arange(0, 16, 1).reshape(4, 4),
    columns = ['column_1', 'column_2', 'column_3', 'column_4'],
    index   = ['a', 'b', 'c', 'd'],
    dtype   = np.float
)

df

column_1  column_2  column_3  column_4
a       0.0       1.0       2.0       3.0
b       4.0       5.0       6.0       7.0
c       8.0       9.0      10.0      11.0
d      12.0      13.0      14.0      15.0

In [8]:
df.astype(np.int)

column_1  column_2  column_3  column_4
a         0         1         2         3
b         4         5         6         7
c         8         9        10        11
d        12        13        14        15

It can be done in an alternative manner

In [9]:
df = pd.DataFrame(
    {
      'column_1': [0,  4,  8, 12],
      'column_2': [1,  5,  9, 13],
      'column_3': [2,  6, 10, 14],
      'column_4': [3,  7, 11, 15]
    },
    index   = ['a', 'b', 'c', 'd']
)

df

column_1  column_2  column_3  column_4
a         0         1         2         3
b         4         5         6         7
c         8         9        10        11
d        12        13        14        15

It is worth mentioning that the unerlying data can be accesed under `values` attribute

In [10]:
df.values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

What's important Pandas DataFrames can handle entires of different type. In the most common situation different columns will have different types.

In [11]:
df = pd.DataFrame(
    {
      'integers': [0,   1,   2,  3],
      'floats':   [1.0, 2.0, 3,  4],
      'booleans': [True, False, True, False],
      'arbitrary objects':  [0, 1.0, 'abc', False]
    }
)

df

integers  floats  booleans arbitrary objects
0         0     1.0      True                 0
1         1     2.0     False                 1
2         2     3.0      True               abc
3         3     4.0     False             False

In [12]:
df.dtypes

integers               int64
floats               float64
booleans                bool
arbitrary objects     object
dtype: object

Another available creation methods are listed below
- `pd.DataFrame.from_dict`
- `pd.DataFrame.from_records`

You can read about them here: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html

### Loading data
Let us peek into the CSV file conveniently provided in the Google Colab runtime

In [13]:
!head './sample_data/california_housing_train.csv'

"longitude","latitude","housing_median_age","total_rooms","total_bedrooms","population","households","median_income","median_house_value"
-114.310000,34.190000,15.000000,5612.000000,1283.000000,1015.000000,472.000000,1.493600,66900.000000
-114.470000,34.400000,19.000000,7650.000000,1901.000000,1129.000000,463.000000,1.820000,80100.000000
-114.560000,33.690000,17.000000,720.000000,174.000000,333.000000,117.000000,1.650900,85700.000000
-114.570000,33.640000,14.000000,1501.000000,337.000000,515.000000,226.000000,3.191700,73400.000000
-114.570000,33.570000,20.000000,1454.000000,326.000000,624.000000,262.000000,1.925000,65500.000000
-114.580000,33.630000,29.000000,1387.000000,236.000000,671.000000,239.000000,3.343800,74000.000000
-114.580000,33.610000,25.000000,2907.000000,680.000000,1841.000000,633.000000,2.676800,82400.000000
-114.590000,34.830000,41.000000,812.000000,168.000000,375.000000,158.000000,1.708300,48500.000000
-114.590000,33.610000,34.000000,4789.000000,1175.000000,3134.000000

and load it using `pd._read_csv` method.

In [14]:
pd.read_csv('./sample_data/california_housing_train.csv')

longitude  latitude  ...  median_income  median_house_value
0        -114.31     34.19  ...         1.4936             66900.0
1        -114.47     34.40  ...         1.8200             80100.0
2        -114.56     33.69  ...         1.6509             85700.0
3        -114.57     33.64  ...         3.1917             73400.0
4        -114.57     33.57  ...         1.9250             65500.0
...          ...       ...  ...            ...                 ...
16995    -124.26     40.58  ...         2.3571            111400.0
16996    -124.27     40.69  ...         2.5179             79000.0
16997    -124.30     41.84  ...         3.0313            103600.0
16998    -124.30     41.80  ...         1.9797             85800.0
16999    -124.35     40.54  ...         3.0147             94600.0

[17000 rows x 9 columns]

In Pandas it is also possible to load JSON files.

In [15]:
!head './sample_data/anscombe.json'

[
  {"Series":"I", "X":10.0, "Y":8.04},
  {"Series":"I", "X":8.0, "Y":6.95},
  {"Series":"I", "X":13.0, "Y":7.58},
  {"Series":"I", "X":9.0, "Y":8.81},
  {"Series":"I", "X":11.0, "Y":8.33},
  {"Series":"I", "X":14.0, "Y":9.96},
  {"Series":"I", "X":6.0, "Y":7.24},
  {"Series":"I", "X":4.0, "Y":4.26},
  {"Series":"I", "X":12.0, "Y":10.84},


In [16]:
pd.read_json('./sample_data/anscombe.json')

Series   X      Y
0       I  10   8.04
1       I   8   6.95
2       I  13   7.58
3       I   9   8.81
4       I  11   8.33
5       I  14   9.96
6       I   6   7.24
7       I   4   4.26
8       I  12  10.84
9       I   7   4.81
10      I   5   5.68
11     II  10   9.14
12     II   8   8.14
13     II  13   8.74
14     II   9   8.77
15     II  11   9.26
16     II  14   8.10
17     II   6   6.13
18     II   4   3.10
19     II  12   9.13
20     II   7   7.26
21     II   5   4.74
22    III  10   7.46
23    III   8   6.77
24    III  13  12.74
25    III   9   7.11
26    III  11   7.81
27    III  14   8.84
28    III   6   6.08
29    III   4   5.39
30    III  12   8.15
31    III   7   6.42
32    III   5   5.73
33     IV   8   6.58
34     IV   8   5.76
35     IV   8   7.71
36     IV   8   8.84
37     IV   8   8.47
38     IV   8   7.04
39     IV   8   5.25
40     IV  19  12.50
41     IV   8   5.56
42     IV   8   7.91
43     IV   8   6.89

## Other I/O functionalities
They are listed here https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html and are suitable for: XML, HDF, Feather, Parquet files as well as for interaction with various databases and much more.

## Handling missing data and duplicates

In the real world it's often the case that there are missing or duplicate values in the dataset. They can be easily delt with in Pandas.

In [17]:
df = pd.DataFrame([
  [0,       1     ],
  [2,       0     ],
  [2,       np.nan],
  [np.nan,  np.nan]
])

df

0    1
0  0.0  1.0
1  2.0  0.0
2  2.0  NaN
3  NaN  NaN

Incomplete observations can be filtered out.

In [18]:
df.dropna()

0    1
0  0.0  1.0
1  2.0  0.0

In [19]:
df.dropna(how='all')

0    1
0  0.0  1.0
1  2.0  0.0
2  2.0  NaN

It is also possible to "fill the gaps".

In [20]:
df.fillna(0)

0    1
0  0.0  1.0
1  2.0  0.0
2  2.0  0.0
3  0.0  0.0

In [21]:
df.fillna(0).drop_duplicates()

0    1
0  0.0  1.0
1  2.0  0.0
3  0.0  0.0

In [22]:
df.fillna({0: 0, 1: 1})

0    1
0  0.0  1.0
1  2.0  0.0
2  2.0  1.0
3  0.0  1.0

## Data access

Let us observe how we can access and manipulate DataFrame structure.

In [23]:
df = pd.read_csv('./sample_data/california_housing_train.csv')
df

longitude  latitude  ...  median_income  median_house_value
0        -114.31     34.19  ...         1.4936             66900.0
1        -114.47     34.40  ...         1.8200             80100.0
2        -114.56     33.69  ...         1.6509             85700.0
3        -114.57     33.64  ...         3.1917             73400.0
4        -114.57     33.57  ...         1.9250             65500.0
...          ...       ...  ...            ...                 ...
16995    -124.26     40.58  ...         2.3571            111400.0
16996    -124.27     40.69  ...         2.5179             79000.0
16997    -124.30     41.84  ...         3.0313            103600.0
16998    -124.30     41.80  ...         1.9797             85800.0
16999    -124.35     40.54  ...         3.0147             94600.0

[17000 rows x 9 columns]

### describe & info
Once the dataframe is loaded `describe` and `info`methods provide an easy way to obtain a high level view of the underlying data.

In [24]:
df.describe()

longitude      latitude  ...  median_income  median_house_value
count  17000.000000  17000.000000  ...   17000.000000        17000.000000
mean    -119.562108     35.625225  ...       3.883578       207300.912353
std        2.005166      2.137340  ...       1.908157       115983.764387
min     -124.350000     32.540000  ...       0.499900        14999.000000
25%     -121.790000     33.930000  ...       2.566375       119400.000000
50%     -118.490000     34.250000  ...       3.544600       180400.000000
75%     -118.000000     37.720000  ...       4.767000       265000.000000
max     -114.310000     41.950000  ...      15.000100       500001.000000

[8 rows x 9 columns]

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB


### head & tail
we can use these methods to look at the first and last entries

In [26]:
df.head()

longitude  latitude  ...  median_income  median_house_value
0    -114.31     34.19  ...         1.4936             66900.0
1    -114.47     34.40  ...         1.8200             80100.0
2    -114.56     33.69  ...         1.6509             85700.0
3    -114.57     33.64  ...         3.1917             73400.0
4    -114.57     33.57  ...         1.9250             65500.0

[5 rows x 9 columns]

In [27]:
df.tail()

longitude  latitude  ...  median_income  median_house_value
16995    -124.26     40.58  ...         2.3571            111400.0
16996    -124.27     40.69  ...         2.5179             79000.0
16997    -124.30     41.84  ...         3.0313            103600.0
16998    -124.30     41.80  ...         1.9797             85800.0
16999    -124.35     40.54  ...         3.0147             94600.0

[5 rows x 9 columns]

In [28]:
df.head(8)

longitude  latitude  ...  median_income  median_house_value
0    -114.31     34.19  ...         1.4936             66900.0
1    -114.47     34.40  ...         1.8200             80100.0
2    -114.56     33.69  ...         1.6509             85700.0
3    -114.57     33.64  ...         3.1917             73400.0
4    -114.57     33.57  ...         1.9250             65500.0
5    -114.58     33.63  ...         3.3438             74000.0
6    -114.58     33.61  ...         2.6768             82400.0
7    -114.59     34.83  ...         1.7083             48500.0

[8 rows x 9 columns]

### rename
can be used to rename column labels.

In [29]:
df.rename(columns={'longitude': 'lon', 'latitude': 'lat'})

lon    lat  ...  median_income  median_house_value
0     -114.31  34.19  ...         1.4936             66900.0
1     -114.47  34.40  ...         1.8200             80100.0
2     -114.56  33.69  ...         1.6509             85700.0
3     -114.57  33.64  ...         3.1917             73400.0
4     -114.57  33.57  ...         1.9250             65500.0
...       ...    ...  ...            ...                 ...
16995 -124.26  40.58  ...         2.3571            111400.0
16996 -124.27  40.69  ...         2.5179             79000.0
16997 -124.30  41.84  ...         3.0313            103600.0
16998 -124.30  41.80  ...         1.9797             85800.0
16999 -124.35  40.54  ...         3.0147             94600.0

[17000 rows x 9 columns]

### Accessing a subset of data

To select multiple columns specify list of labels within square brackets.

In [30]:
df[['longitude', 'latitude']]

longitude  latitude
0        -114.31     34.19
1        -114.47     34.40
2        -114.56     33.69
3        -114.57     33.64
4        -114.57     33.57
...          ...       ...
16995    -124.26     40.58
16996    -124.27     40.69
16997    -124.30     41.84
16998    -124.30     41.80
16999    -124.35     40.54

[17000 rows x 2 columns]

Single column can be retrieved by specifying its name within square brackets. Note that this will yield a `Series` object which behaves a little different than DataFrames, but in general is a representation of single varaible values.

In [31]:
df['longitude']

0       -114.31
1       -114.47
2       -114.56
3       -114.57
4       -114.57
          ...  
16995   -124.26
16996   -124.27
16997   -124.30
16998   -124.30
16999   -124.35
Name: longitude, Length: 17000, dtype: float64

If column name does not contain spaces and other special character it can accesed as an attribute.

In [32]:
df.longitude

0       -114.31
1       -114.47
2       -114.56
3       -114.57
4       -114.57
          ...  
16995   -124.26
16996   -124.27
16997   -124.30
16998   -124.30
16999   -124.35
Name: longitude, Length: 17000, dtype: float64

Subset of a DataFrame can be selected using `loc` attribute. You need to specify index and column labels. Note that it supports slicing with respoect to column names.

In [33]:
df.loc[5:10, 'population': 'median_house_value']

population  households  median_income  median_house_value
5        671.0       239.0         3.3438             74000.0
6       1841.0       633.0         2.6768             82400.0
7        375.0       158.0         1.7083             48500.0
8       3134.0      1056.0         2.1782             58400.0
9        787.0       271.0         2.1908             48100.0
10      2434.0       824.0         2.6797             86500.0

It also possible to select data with slices correspong to indices and columns **positions** (as in NumPy).

In [34]:
df.iloc[5:10, -4:]

population  households  median_income  median_house_value
5       671.0       239.0         3.3438             74000.0
6      1841.0       633.0         2.6768             82400.0
7       375.0       158.0         1.7083             48500.0
8      3134.0      1056.0         2.1782             58400.0
9       787.0       271.0         2.1908             48100.0

Boolean arrays (including boolean `Series` object) can be used as well.

In [35]:
index = df.median_house_value < 25000
index

0        False
1        False
2        False
3        False
4        False
         ...  
16995    False
16996    False
16997    False
16998    False
16999    False
Name: median_house_value, Length: 17000, dtype: bool

In [36]:
df.loc[index, 'median_house_value']

264      22500.0
568      14999.0
3226     14999.0
7182     17500.0
11653    22500.0
15499    22500.0
16643    14999.0
16801    14999.0
Name: median_house_value, dtype: float64

It is also possible to do

In [38]:
df[index]

longitude  latitude  ...  median_income  median_house_value
264      -116.57     35.43  ...         2.7138             22500.0
568      -117.02     36.40  ...         2.1000             14999.0
3226     -117.86     34.24  ...         4.1932             14999.0
7182     -118.33     34.15  ...         2.3667             17500.0
11653    -121.29     37.95  ...         0.7917             22500.0
15499    -122.32     37.93  ...         2.6750             22500.0
16643    -122.74     39.71  ...         1.6607             14999.0
16801    -123.17     40.31  ...         0.5360             14999.0

[8 rows x 9 columns]

## Merging dataframes
can be used to merge multiple arrays into one.


In [39]:
df_1 = pd.DataFrame(np.arange(9).reshape(3, 3), columns=['a', 'b', 'c'], index=[0, 1, 2])
df_2 = pd.DataFrame(np.arange(9).reshape(3, 3), columns=['b', 'c', 'd'], index=[1, 2, 3])

In [40]:
df_1

a  b  c
0  0  1  2
1  3  4  5
2  6  7  8

In [41]:
df_2

b  c  d
1  0  1  2
2  3  4  5
3  6  7  8

There are to basic methods for merging dataframes. The first one is `append` that concatenates dataframes along the index.

In [42]:
df_1.append(df_2)

a  b  c    d
0  0.0  1  2  NaN
1  3.0  4  5  NaN
2  6.0  7  8  NaN
1  NaN  0  1  2.0
2  NaN  3  4  5.0
3  NaN  6  7  8.0

The second one is join that concatenates dataframes along the columns.

In [43]:
df_1.join(df_2, how='outer', lsuffix='_left', rsuffix='_right')

a  b_left  c_left  b_right  c_right    d
0  0.0     1.0     2.0      NaN      NaN  NaN
1  3.0     4.0     5.0      0.0      1.0  2.0
2  6.0     7.0     8.0      3.0      4.0  5.0
3  NaN     NaN     NaN      6.0      7.0  8.0

These two methods are special cases of more general function `concat` that allows more advanced oprations. There is also `merge` method which makes use of database-like joins.

All of these methods are described and explained here: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html

## Operations on dataframes
Pandas can be used to perfrom mathematical and other operations on the underlying data.

### Elementwise operations
The most common use case is to create a new column being a result of some operation on existing columns.

In [44]:
people_per_household = df.population / df.households
people_per_household

0        2.150424
1        2.438445
2        2.846154
3        2.278761
4        2.381679
           ...   
16995    2.457995
16996    2.567742
16997    2.728070
16998    2.715481
16999    2.985185
Length: 17000, dtype: float64

In [45]:
df['people_per_household'] = people_per_household
df

longitude  latitude  ...  median_house_value  people_per_household
0        -114.31     34.19  ...             66900.0              2.150424
1        -114.47     34.40  ...             80100.0              2.438445
2        -114.56     33.69  ...             85700.0              2.846154
3        -114.57     33.64  ...             73400.0              2.278761
4        -114.57     33.57  ...             65500.0              2.381679
...          ...       ...  ...                 ...                   ...
16995    -124.26     40.58  ...            111400.0              2.457995
16996    -124.27     40.69  ...             79000.0              2.567742
16997    -124.30     41.84  ...            103600.0              2.728070
16998    -124.30     41.80  ...             85800.0              2.715481
16999    -124.35     40.54  ...             94600.0              2.985185

[17000 rows x 10 columns]

More general function can be applied with use of `apply` method

In [46]:
def func(row):
  if row.latitude > 0:
    ns_hemisphere = 'N'
  else:
    ns_hemisphere = 'S'
  
  if row.longitude > 0:
    ew_hemisphere = 'E'
  else:
    ew_hemisphere = 'W'

  gps_label = f"{abs(row.latitude)} {ns_hemisphere}, {abs(row.longitude)} {ew_hemisphere}"

  return gps_label
  
df.apply(func, axis=1).head()

0    34.19 N, 114.31 W
1     34.4 N, 114.47 W
2    33.69 N, 114.56 W
3    33.64 N, 114.57 W
4    33.57 N, 114.57 W
dtype: object

### GroupBy
can be used to split a dataframe into multiple based on some condition/values

In [47]:
values = df.median_house_value.round(-4)
values

0         70000.0
1         80000.0
2         90000.0
3         70000.0
4         70000.0
           ...   
16995    110000.0
16996     80000.0
16997    100000.0
16998     90000.0
16999     90000.0
Name: median_house_value, Length: 17000, dtype: float64

In [48]:
gb = df.groupby(values)
gb

Groups labels and indices can be accessed under `groups` attribute and themselves with the use of `get_group` method.

In [49]:
gb.groups

{10000.0: [568, 3226, 16643, 16801], 20000.0: [17, 264, 7182, 11653, 15499], 30000.0: [19, 110, 116, 157, 9636, 9637, 9641, 10026, 10692, 10935, 11902, 12341, 12671], 40000.0: [14, 18, 20, 36, 46, 50, 59, 115, 126, 158, 288, 427, 497, 1902, 2151, 2591, 3513, 6592, 9043, 9065, 9071, 9086, 9094, 9095, 9122, 9255, 9289, 9390, 9392, 9468, 9486, 9494, 9624, 9647, 9685, 9689, 9743, 9948, 9975, 10050, 10053, 10055, 10125, 10186, 10359, 10470, 10648, 10791, 11306, 11652, 11752, 11796, 12364, 12382, 12478, 13341, 15653, 16823, 16887], 50000.0: [7, 9, 12, 22, 24, 47, 51, 74, 109, 113, 121, 122, 123, 124, 125, 138, 144, 170, 182, 242, 266, 317, 1104, 1863, 2674, 2709, 3054, 4765, 4766, 4767, 8009, 8892, 8897, 8912, 8955, 8966, 9010, 9027, 9028, 9029, 9036, 9040, 9042, 9045, 9046, 9051, 9055, 9056, 9057, 9058, 9059, 9060, 9061, 9062, 9064, 9075, 9077, 9080, 9081, 9082, 9083, 9084, 9090, 9096, 9097, 9099, 9100, 9104, 9105, 9106, 9110, 9114, 9117, 9121, 9130, 9137, 9138, 9157, 9159, 9161, 9162, 9181

In [50]:
gb.get_group(10000)

longitude  latitude  ...  median_house_value  people_per_household
568      -117.02     36.40  ...             14999.0              2.987805
3226     -117.86     34.24  ...             14999.0              2.791111
16643    -122.74     39.71  ...             14999.0              2.236842
16801    -123.17     40.31  ...             14999.0              2.250000

[4 rows x 10 columns]

The main use case of the `groupby` functionality is to split dataframe based on some condition, perform some aggregation within groups and then join the results. An example of such an operation is calcualtin mean within each group.

In [51]:
gb.mean().head()

longitude  ...  people_per_household
median_house_value              ...                      
10000.0            -120.197500  ...              2.566440
20000.0            -118.632000  ...              3.115305
30000.0            -118.980000  ...              2.779726
40000.0            -118.979661  ...              3.709225
50000.0            -119.536537  ...              3.466028

[5 rows x 10 columns]

You can read more about `groupby` funcionality in teh pandas user guide: https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html

## Pandas Exercises

### Pandas exercise: IMDB movies

In this exercise we will look into IMDB Top 1000 movies dataset. We will first load it into a dataframe.


In [52]:
url = "https://raw.githubusercontent.com/peetck/IMDB-Top1000-Movies/master/IMDB-Movie-Data.csv"
df = pd.read_csv(url)
df

Rank                    Title  ... Revenue (Millions) Metascore
0       1  Guardians of the Galaxy  ...             333.13        76
1       2               Prometheus  ...             126.46        65
2       3                    Split  ...             138.12        62
3       4                     Sing  ...             270.32        59
4       5            Suicide Squad  ...             325.02        40
..    ...                      ...  ...                ...       ...
995   996     Secret in Their Eyes  ...               0.00        45
996   997          Hostel: Part II  ...              17.54        46
997   998   Step Up 2: The Streets  ...              58.01        50
998   999             Search Party  ...               0.00        22
999  1000               Nine Lives  ...              19.64        11

[1000 rows x 12 columns]

Part 1.

1. How much should movie earn to be among 2% best earning movies?
2. Select movies that earned more than this value.
3. Calculate their mean rating.

In [60]:
### YOUR CODE BEGINS HERE ###
answer = np.mean(df.nlargest(n=int(df.shape[0]*0.02), columns=['Revenue (Millions)'])['Rating'])
### YOUR CODE ENDS HERE ###

In [61]:
# Your code in cell(s) above
assert np.isclose(answer, 7.615)

Part 2.
1. Calculate mean metascore and mean revenue per director. (use groupby)
2. Restrict results to the directors that directed more than four movies. (look up `value_counts` method)
3. Sort the results with respect to the metascore and display the rating as a dataframe.
4. Who is the 3rd director it this rating and what is his/her mean revenue?

In [139]:
df_temp = df.groupby('Director').agg({'Director': 'count', 'Metascore': 'mean', 'Revenue (Millions)': 'mean'})
df_temp = df_temp[df_temp['Director'] > 4]
df_temp = df_temp.drop(columns='Director', axis=1)
df_sorted = df_temp.sort_values('Metascore', ascending=False)
director = df_sorted.iloc[[2]]['Revenue (Millions)'].index[0]
revenue = df_sorted.iloc[[2]]['Revenue (Millions)'][0]
df_sorted

Metascore  Revenue (Millions)
Director                                         
David Fincher       78.600000          105.544000
Martin Scorsese     77.000000           91.622000
Denis Villeneuve    75.600000           43.242000
Danny Boyle         75.000000           36.680000
Christopher Nolan   74.800000          303.018000
J.J. Abrams         74.600000          336.690000
Woody Allen         69.400000           28.238000
David Yates         68.500000          271.751667
Ridley Scott        59.750000           89.882500
Peter Berg          57.400000          102.266000
Justin Lin          57.200000          164.958000
Antoine Fuqua       52.400000           78.642000
Zack Snyder         48.000000          195.148000
Michael Bay         43.833333          236.886667
Paul W.S. Anderson  40.333333           34.820000
M. Night Shyamalan  40.000000           61.748333

In [140]:
print(f"Mean revenue of {director} is {revenue:.3f}.")
assert np.isclose(revenue, 43.242)

Mean revenue of Denis Villeneuve is 43.242.


### Pandas exercises: Anscombe's quartet

In this exercise we will look into so called Anscombe's quartet that visualizes pitfalls of some statistics used to describe datasets

![image](https://upload.wikimedia.org/wikipedia/commons/e/ec/Anscombe%27s_quartet_3.svg)

Firstly, let us load the data.

In [141]:
df = pd.read_json("./sample_data/anscombe.json")
df

Series   X      Y
0       I  10   8.04
1       I   8   6.95
2       I  13   7.58
3       I   9   8.81
4       I  11   8.33
5       I  14   9.96
6       I   6   7.24
7       I   4   4.26
8       I  12  10.84
9       I   7   4.81
10      I   5   5.68
11     II  10   9.14
12     II   8   8.14
13     II  13   8.74
14     II   9   8.77
15     II  11   9.26
16     II  14   8.10
17     II   6   6.13
18     II   4   3.10
19     II  12   9.13
20     II   7   7.26
21     II   5   4.74
22    III  10   7.46
23    III   8   6.77
24    III  13  12.74
25    III   9   7.11
26    III  11   7.81
27    III  14   8.84
28    III   6   6.08
29    III   4   5.39
30    III  12   8.15
31    III   7   6.42
32    III   5   5.73
33     IV   8   6.58
34     IV   8   5.76
35     IV   8   7.71
36     IV   8   8.84
37     IV   8   8.47
38     IV   8   7.04
39     IV   8   5.25
40     IV  19  12.50
41     IV   8   5.56
42     IV   8   7.91
43     IV   8   6.89

For each series calculate its 
- mean value of $X$
- mean value of $Y$
- sample variance of $X$
- sample variance of $Y$
- covariance beetwen $X$ and $Y$

and verify whether for each series you get
- mean of $X$ = 9,
- var of $X$ = 11,
- mean of $Y$ = 7.5 +- 0.01,
- var of $Y$ = 4.12 +- 0.01,
- cov of $X$ and $Y$ = 5.50 +- 0.01,

(you can try to make use of `aggregate` function of a `GroupBy` object)

In [149]:
### YOUR CODE BEGINS HERE ###
df.groupby('Series').agg({'X': ['mean', 'var'], 'Y': ['mean', 'var']})

### YOUR CODE ENDS HERE ###

X               Y          
       mean   var      mean       var
Series                               
I         9  11.0  7.500000  4.132640
II        9  11.0  7.500909  4.127629
III       9  11.0  7.500000  4.122620
IV        9  11.0  7.500909  4.123249

In [148]:
df.groupby('Series').apply(lambda x: x['X'].cov(x['Y']))

Series
I      5.503
II     5.500
III    5.497
IV     5.499
dtype: float64

<center><img src='https://drive.google.com/uc?id=1PioHCAlQTt8LWChoMysPErSOrxOfAW0R'></center>